<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYpagslu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYpagslu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYpagslu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYpagslu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYpagslu\appDevDebugProjectContainer([
    'container.build_hash' => 'Ypagslu',
    'container.build_id' => '25185981',
    'container.build_time' => 1573315625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYpagslu');
